name: Full Stack CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: client/pnpm-lock.yaml
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build application
        run: pnpm run build
      
      - name: Upload client build
        uses: actions/upload-artifact@v3
        with:
          name: client-build
          path: client/.next
  
  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: server/pnpm-lock.yaml
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build application
        run: pnpm run build
      
      - name: Upload server build
        uses: actions/upload-artifact@v3
        with:
          name: server-build
          path: server/dist